syntax on
set number
set linebreak
set showbreak=+++
set ruler
set backspace=indent,eol,start
set incsearch
set wildmenu
set wildmode=longest,list,full
set autoindent
set autoread
set backspace=2
set backupcopy=yes
set clipboard=unnamed
set directory-=.
set encoding=utf-8
set expandtab
set ignorecase
set incsearch
set laststatus=2
set scrolloff=3
set shiftwidth=2
set showcmd
set smartcase
set softtabstop=2
set tabstop=8
set wildmenu
set wildmode=longest,list,full
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2
set dip=vertical,filler,internal
colorscheme slate
